### ISSUE TITLE
Long show names weird behaviour (cut off, overlapping)

### ISSUE THREAD

**Issue by vodkapmp** [tedhinklater/finimalism#22]
If a show name is more than 1 line it ends up putting any alternate naming (native title usually) and season numbers to the side and overlapping other content.
If the show name in itself is more than 3 lines it is also cuts off the third line, but only on the show page itself. On a season page it will show the entire 3 lines of the name.
Examples:
![image](https://github.com/user-attachments/assets/e4e53d97-ccc3-42b0-bb4f-c8452f971d68)
![image](https://github.com/user-attachments/assets/d00ec921-39dd-4aa3-8f2c-c72b06f850a3)

**Comment by tedhinklater** [comment]
Thanks for the screenshots, that's [fixed](https://github.com/tedhinklater/finimalism/commit/2ee946b54ccc0305ce35f1908f2f7fab7dbe2c05) now

The update should come through shortly, in the meantime you can apply the fix manually by adding this snippet to your CSS box

```css
.layout-desktop .itemName.infoText.parentNameLast, .layout-tv .itemName.infoText.parentNameLast {white-space:nowrap;}
```

**Comment by tedhinklater** [comment]
edit (better fix): 

```css

.layout-desktop .itemName.infoText.parentNameLast,
.layout-tv .itemName.infoText.parentNameLast {
  display: -webkit-box !important;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 2;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: normal;
}

.layout-desktop .itemName.infoText.originalTitle,
.layout-tv .itemName.infoText.originalTitle {
  position: absolute;
  top: 6em;
  left: 1em;
  font-size: 1em;
  width: 23.75em;
}

```

![Screenshot 2024-12-14 141612](https://github.com/user-attachments/assets/c4df56b5-edc0-42ca-90be-29e3ce8b22cf)
