### ISSUE TITLE
Audio and subtitles control not visible on 21:9 1440p screen

### ISSUE THREAD

**Issue by Vetrix68** [tedhinklater/finimalism#24]
The audio and subtitles track control is not visible on screen of resolution of 3440x1440 as shown below (scrolling doesn't change anything). If i change the font-size then jellyfin on my tv is too small.

![obraz](https://github.com/user-attachments/assets/9e8f56ee-7223-4f25-919d-62d7554f5334)

**Comment by tedhinklater** [comment]
Hey thanks for providing screenshots & resolution, I've added a [fix](https://github.com/tedhinklater/finimalism/commit/7a66832737e237b19b0a6fa7b98c9ef290a4376c) 

If you could test it with this and let me know if anything needs changing, that would be greatly appreciated!

```css
@import url("https://cdn.jsdelivr.net/gh/tedhinklater/finimalism@main/finimalism-just-black.css");
@media (min-aspect-ratio: 20/9) and (max-aspect-ratio: 22/9) and (min-width: 2500px) {body {font-size: 166%!important;}.layout-desktop .detailSectionContent,.layout-tv .detailSectionContent {font-size: 1.2em;}.layout-desktop .itemExternalLinks.focuscontainer-x, .layout-tv .itemExternalLinks.focuscontainer-x {font-size: 0.9em !important;width: 18em;top: 51em;}}
```

**Comment by Vetrix68** [comment]
Sorry for long reply. I think it's still wrong. But resizing the window is very jumpy, it changes a couple of times.

https://github.com/user-attachments/assets/ce15c116-d173-45d0-985e-0b0fe661f6a1

**Comment by tedhinklater** [comment]
> resizing the window is very jumpy, it changes a couple of times

People have different sized screens (like yourself) and I have to set up media declarations so they all have the same look (hopefully) on any size. I'll get there eventually

Thanks for the video, I believe this should work for your 21:9 1440p screen

```css

@media (min-width: 3500px) {
	body {
		font-size: 200%;
	}
	.cardOverlayButton-hover {
		font-size: 0.95em;
	}
}

@media (min-aspect-ratio: 20/9) and (max-aspect-ratio: 22/9) and (min-width: 2500px) and (max-width: 3499px) {
	body {
		font-size: 150% !important;
	}
	.layout-desktop .detailSectionContent,
	.layout-tv .detailSectionContent {
		font-size: 1.2em;
	}
	.layout-desktop .itemExternalLinks.focuscontainer-x, 
	.layout-tv .itemExternalLinks.focuscontainer-x {
		font-size: 0.9em !important;
		width: 18em;
		top: 51em;
	}
}

```

Thanks for your patience & assistance with this as well, it's still a work in progress but it's getting there!

Merry Christmas
