### ISSUE TITLE
Play button unavailable 

### ISSUE THREAD

**Issue by aneeshdash** [tedhinklater/finimalism#26]
I updated jellyfin server version to 10.10.3 and the play button disappeared from all media in the jellyfin app and chrome on ipad. The play button is visible on the default theme if I remove the css

**Comment by tedhinklater** [comment]
I've added a [fix](https://github.com/tedhinklater/finimalism/commit/acfddeaeabd47b6f0890789256c7301589181070) it'll update shortly but you can apply it manually now with this snippet

```css

@import url("https://cdn.jsdelivr.net/gh/tedhinklater/finimalism@main/finimalism7.css");
@media (orientation: portrait) and (min-width: 800px) {.layout-mobile .itemMiscInfo.itemMiscInfo-primary {padding-left: 8vw;padding-left: 21vw;}.layout-mobile [dir="ltr"] .mainDetailButtons {justify-content: space-evenly;}.layout-mobile [dir="ltr"] .mainDetailButtons {padding-left: 24vw;}}@media (min-width: 65em) {.layout-mobile [dir="ltr"] .mainDetailButtons {font-size: 85%;font-size: 90%;margin-bottom: 0em;margin-top: 2em;margin-top: 4em;}}

```
