### ISSUE TITLE
[TV or Controller input] Add highlights at user settings

### ISSUE THREAD

**Issue by TharathielCB** [tedhinklater/finimalism#30]
Hi, I like your CSS design very much. 
When using it on my lg webOS I can't see the current selected line in the user settings tab.
On the TV I have to use the remote/controller input obviously.
 I know this is not a big deal, but I liked to share it with you :)

Continue with your great work.

Greetings.

![Image](https://github.com/user-attachments/assets/20b501da-db28-4c07-9de5-dfc9d53eb8e4)

**Comment by tedhinklater** [comment]
that should be fixed now in the latest (use this if it hasn't updated on your end)

```css
@import url("https://cdn.jsdelivr.net/gh/tedhinklater/finimalism@main/finimalism7.css");
#myPreferencesMenuPage .verticalSection-extrabottompadding .emby-button:focus .listItemBodyText {border: 1px solid white;border-radius: 1em;}
```
