### ISSUE TITLE
[TV or Controller input] wrong direction at remote input

### ISSUE THREAD

**Issue by TharathielCB** [tedhinklater/finimalism#31]
Hi, and here is a second problem I encountered. 
On the movie selection the direction of the remote input seems to work not properly. 
This is the behaviour:
Pressing on the remote -> direction on the screen
Down -> Down left (Yellow Arrow)
Up -> up left (Red Arrow)
Left -> up left (Blue Arrow)
Right -> up right (Green Arrow)

![Image](https://github.com/user-attachments/assets/bbd581c9-3267-4fed-8eb6-5dc699c36cc0)

**Comment by tedhinklater** [comment]
thanks for the pics I'll fix it asap

**Comment by tedhinklater** [comment]
That should be fixed now in the latest, the jsdelivr import link will update shortly but if you want it sooner it can be applied with this:

```css
@import url("https://cdn.jsdelivr.net/gh/tedhinklater/finimalism@main/finimalism7.css");
.layout-tv .card:focus {transform: unset;}
```
