### ISSUE TITLE
Paged Movie Library Navigation

### ISSUE THREAD

**Issue by d1g-g1t** [tedhinklater/finimalism#32]
Thank you for the great theme! I ran into an issue while navigating the movie library using the paged navigation.

When navigating to the next page, it does not start at the top again, forcing you to manually scroll back up to the top. It happens on both the web interface and the Jellyfin Media Player. As far as I can tell, it only happens in the Movies Library.

Scrolling works normally when removing theme.

**Comment by tedhinklater** [comment]
I genuinely thought that was just Jellyfin
![Image](https://github.com/user-attachments/assets/426d4131-1e1a-42cd-a4ad-182902769df8)

It's been [fixed](https://github.com/tedhinklater/finimalism/commit/a4f033c294fdd60c06ee8e390751f96faae9b77b) the import link should update shortly, in the meantime you can add this to your CSS to apply the fix instantly

```css
@import url("https://cdn.jsdelivr.net/gh/tedhinklater/finimalism@main/finimalism7.css");
@media all and (min-width: 100em){#indexPage,#moviesPage,#tvRecommendedPage,#musicRecommendedPage {overflow-y: unset;}}
@media all and (max-width: 100em){#indexPage,#moviesPage,#tvRecommendedPage,#musicRecommendedPage {overflow-y: unset;}}
```

Thanks for letting me know!
