### ISSUE TITLE
icons alignment not good

### ISSUE THREAD

**Issue by skaffa** [tedhinklater/finimalism#33]
![Image](https://github.com/user-attachments/assets/65c91f0c-ed2f-4db1-a227-9e73b487ccfc)

**Comment by tedhinklater** [comment]
that's fixed now, the import link will update shortly. If you want to apply the fix immediately you can add this to your css


```css
@import url("https://cdn.jsdelivr.net/gh/tedhinklater/finimalism@main/finimalism7.css");
.layout-desktop #songsTab .itemsContainer.vertical-list {max-width: 80vw !important;} .layout-desktop #songsTab .itemsContainer.vertical-list .listItemBody.itemAction {min-width: 38vw;}
```
