### ISSUE TITLE
"save" button hidden at bottom of page, unless zooming out

### ISSUE THREAD

**Issue by skaffa** [tedhinklater/finimalism#35]
![Image](https://github.com/user-attachments/assets/21b6c042-5672-4ac9-a92d-0254f15504cc)

**Comment by skaffa** [comment]
only when a song is playing

**Comment by tedhinklater** [comment]
Thanks for letting me know, it's been fixed, should come automatically soon but can be applied with this css

```css
@import url("https://cdn.jsdelivr.net/gh/tedhinklater/finimalism@main/finimalism-just-black.css");
.content-primary {padding-bottom: 5em !important;}
```
