### ISSUE TITLE
Bug: When grouping versions for TV-shows it breaks the episode page

### ISSUE THREAD

**Issue by KiimaRo** [tedhinklater/finimalism#51]
When you group versions for a TV-show, you will break the whole page. This doesn't happen for movies however.
![Image](https://github.com/user-attachments/assets/0035163f-81dc-4cce-b5f9-4e0f75a2010f)

**Comment by tedhinklater** [comment]
Hey thanks that should be [fixed](https://github.com/tedhinklater/finimalism/commit/524011eff5aff1844fe1de16977d7a41047d3793)
the problem was no metadata = no height.


the jsdelivr import link will update shortly but to apply the fix quickly, add this to your CSS

```css
.padded-bottom-page {
	position: absolute;
	min-height: 35.1%;
}
```
