### ISSUE TITLE
Video media thumbnails exceeding right-hand edge of application window.

### ISSUE THREAD

**Issue by PaulFromNZ** [tedhinklater/finimalism#52]
It appears that since commit 524011e that library view for video media thumbnails overlap the right-hand edge of the display area, covering the vertical A-Z links and creating a horizontal scroll bar at the bottom of the page.

I thought initially that the issue was at my end due to coincidentally "upgrading" to Windows 11 at practically the same time.
However, I've confirmed on other machines and user accounts at different resolutions and display scaling on Win11 and 10 that the issue is apparent for all devices, having tried with both Jellyfin Media Player and Firefox.

The issue does not occur for square thumbnails used for music albums.

Please refer to the attached sample image of the issue.

![Image](https://github.com/user-attachments/assets/7b84dcbe-d958-4567-8074-779c8fa6ae3b)

**Comment by tedhinklater** [comment]
Thanks for the tip, that should be [fixed](https://github.com/tedhinklater/finimalism/commit/4a3368a7c762aaaf7646f7155657179285d045ac) now, the update will come through shortly, but to apply the fix immediately add this to your css import lines:

```css
.layout-desktop .page.libraryPage.noSecondaryNavPage.mainAnimatedPage .vertical-wrap.itemsContainer.centered,
.layout-tv .page.libraryPage.noSecondaryNavPage.mainAnimatedPage .vertical-wrap.itemsContainer.centered {
	max-width: 90%;
}
```
