### ISSUE TITLE
Is there a way to have this without the compact episode list?

### ISSUE THREAD

**Issue by Mr3DAlien** [tedhinklater/finimalism#8]
I like everything about this theme, except the compact episode list. I personally think it always looks horrible if episode pictures where not made specifically for it. Is there a way to get it back the old way, or even better have them next to each other?

**Comment by tedhinklater** [comment]
Hey if you add this snippet to your custom css box it should look neater

```css
#childrenContent .childrenItemsContainer .listItemImage.listItemImage-large.itemAction.lazy.non-blurhashable.lazy-image-fadein-fast {
	background-position: 50%;
	height: 9em !important;
	margin-right: .75em;
	width: 16em !important;
	border-radius: 0.2em !important;
	top: 0.5em;
}

#childrenContent .childrenItemsContainer.itemsContainer > * {
  height: 9em;
}
```

**Comment by Mr3DAlien** [comment]
Doesn't see, to work for me!

**Comment by tedhinklater** [comment]
I'm gonna redo the theme (was my first its a bit janky) shouldn't take long

**Comment by Mr3DAlien** [comment]
Thank you so much! It would be really cool if you maybe at the end would gave the user the option to have smaller, normal or videos in a row and they can just choose which one they want. Keep up the good work!

**Comment by tedhinklater** [comment]
Ok if you apply the theme normally (make sure you've emptied your browser cache with Ctrl+F5)
```css
@import url("https://cdn.jsdelivr.net/gh/tedhinklater/finimalism@main/finimalism7.css");
```

And also paste this css, under that import line

```css
#childrenCollapsible .childrenItemsContainer.itemsContainer.padded-right.vertical-list .listItemBody.itemAction {
	position: absolute;
	bottom: 0.25em;
	background: linear-gradient(90deg, rgb(4.314% 1.176% 11.373% / 0.92) 0%, rgb(4.314% 1.176% 11.373% / 0.9199859619140626) 6.25%, rgb(4.313% 1.177% 11.375% / 0.919775390625) 12.5%, rgb(4.309% 1.177% 11.384% / 0.9188629150390626) 18.75%, rgb(4.3% 1.18% 11.408% / 0.9164062500000001) 25%, rgb(4.28% 1.184% 11.459% / 0.9112261962890625) 31.25%, rgb(4.244% 1.192% 11.551% / 0.901806640625) 37.5%, rgb(4.184% 1.205% 11.703% / 0.8862945556640626) 43.75%, rgb(4.093% 1.225% 11.936% / 0.8625) 50%, rgb(3.96% 1.255% 12.276% / 0.8278961181640625) 56.25%, rgb(3.775% 1.296% 12.749% / 0.779619140625) 62.5%, rgb(3.525% 1.352% 13.388% / 0.7144683837890625) 68.75%, rgb(3.197% 1.425% 14.226% / 0.62890625) 75%, rgb(2.776% 1.518% 15.303% / 0.5190582275390625) 81.25%, rgb(2.245% 1.636% 16.66% / 0.380712890625) 87.5%, rgb(1.587% 1.782% 18.34% / 0.20932189941406254) 93.75%, rgb(0.784% 1.961% 20.392% / 0) 100% );
	width: 18vw;
	z-index: 1;
	pointer-events: none;
	height: 1.75em;
	border-bottom-right-radius: 0.75em;
	border-bottom-left-radius: 0.75em;
}

#childrenCollapsible .childrenItemsContainer.itemsContainer.padded-right.vertical-list .listItemBodyText {
	line-height: 0.8em;
	margin-top: -0.2em;
	white-space: nowrap;
}

#childrenCollapsible .childrenItemsContainer.itemsContainer.padded-right.vertical-list .listViewUserDataButtons {
	left: -21em;
	position: relative;
	justify-content: space-between;
	bottom: -9.4em;
	font-size: 0.6em;
	border-top-right-radius: 0.75em;
	border-top-left-radius: 0.75em;
	z-index: 2;
}

#childrenCollapsible .childrenItemsContainer.itemsContainer.padded-right.vertical-list .listViewUserDataButtons .listItemButton.paper-icon-button-light {
	contain: layout style;
	-webkit-flex-shrink: 0;
	flex-shrink: 0;
	margin: 0;
	padding-left: 0.8vw;
	padding-right: 0.8vw;
}

#childrenContent .childrenItemsContainer.itemsContainer.padded-right.vertical-list {
	display: grid;
	grid-template-columns: repeat(auto-fill, minmax(19vw, 1fr));
}

.layout-desktop #childrenContent .childrenItemsContainer.itemsContainer > * {
	width: 24em;
}

#childrenContent .childrenItemsContainer.itemsContainer.padded-right.vertical-list .listItem:hover {
	background: transparent;
	cursor: pointer;
}

#childrenContent .listItemImageButton {
  opacity: 0.5;
}

#childrenContent .listItemImageButton:hover {
  opacity: 1;
}

#childrenContent .listItem-indexnumberleft {
  margin: 0em;
  padding-top: 1.6em;
  padding-left: 0.5em;
  padding-right: 1em;
  z-index: 3;
}

#childrenContent .listItem .secondary.listItemMediaInfo {
	margin-top: 1em;
	padding-left: 0em;
	z-index: 3;
}
```

Be warned that music/album tracks will also be a grid now, it's just how Jellyfin works (they're classed as the same thing) but it should look like a grid now. jsDelivr is down at the moment but when it's up again we can convert that css chunk into an import line

![Screenshot 2024-09-30 031555](https://github.com/user-attachments/assets/acb947a5-3296-4ec5-a579-4e300cffdafb)
